routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('login','LoginController');
Route::resource('registration','RegistrationController', ['middleware' => 'CheckLogin']);



Route::group(['middleware' => 'CheckTime'], function()
{
    Route::group(['middleware' => 'CheckLogout'], function()
      {
			Route::resource('advertise','AdvertiseController');
			Route::resource('advcomment','AdvertiseCommentController');
			Route::resource('profile','ProfileController');
			Route::resource('select','SelectController');
			Route::resource('logout','LogoutController');
			Route::resource('delete','DeletedController');
			Route::resource('mypro','MyProfileController');
			Route::resource('statistic','StatisticsController');
      });

});



Route::resource('sentmail','MailController');

resources/views/login.blade.php
@extends('master')

   @section('title')
        welcome to login here
   @endsection


   @section('content')
                   <div class="row">
     
                        <div class="col-md-5 text-center go-registration">
                           <h5 ><b>don't have an account!!</b></h5>
                           <h5 ><b>click below for registration.</b></h5>

                            <a  href="{{ route('registration.index')}}"> go to registration </a>
                        </div>
                       
                         <div class="col-md-6 col-md-offset-1">
                                <h4 class="first-heading text-center"><b>Welcome to Login Here: </b></h4>
                                  @if ($errors->any())
                                       <div class="alert alert-danger">
                                           <ul>
                                               @foreach ($errors->all() as $error)
                                                   <li>{{ $error }}</li>
                                               @endforeach
                                           </ul>
                                       </div>
                                   @endif
                               
                       <p class="messsage text-center" style="color:red"> {{ session('message') }} </p>

                            
                             {!! Form::open(array('route'=>'login.store')) !!}
                                <div class="w3-card login-card">
                                      <div class="form-group row">
                                             <div class="col-md-3 col-sm-3 col-xs-3">
                                                 <label class="contrl-label" for="email">Email:</label>
                                             </div>
                                             <div class="col-md-9 col-sm-9 col-xs-9">
                                                  <input type="email" class="form-control" name="email"  value="{{ old('email') }}" required>
                                              </div>
                                       </div>

                                    

                                       <div class="form-group row">
                                              <div class="col-md-3 col-sm-3 col-xs-3">
                                                   <label class="control-label" for="password">Password: </label>
                                               </div>
                                               <div class="col-md-9 col-sm-9 col-xs-9">
                                                    <input type="password" class="form-control" name="password"  value="{{ old('password') }}" required> 
                                               </div>
                                       </div>

                                     <!--  ,'onclick'=>'return myFunction1()' -->
                                       {!!Form::submit('submit',array('class'=>'btn btn-success'))!!}
                               </div>
                              {!! Form::close() !!}

                           </div>

                          

                           <div class="col-md-10">
                            <br><br>
                      <h3 class="text-center"> Search Your Prefered House ! </h3>
                    

                             <div class="search">
                        {!! Form::open(['route'=>'login.index','method'=>'GET','class'=>'search-form']) !!}
                               <div class="form-group row">
                                   <div class="col-md-9 col-sm-9 col-xs-9">
                                        <input type="text" name="name"  class="form-control col-md-10" placeholder="  search by area name">
                                    </div>
                                    <div class="col-md-3 col-sm-3 col-xs-3">
                        {!!Form::submit('search',array('class'=>'search-button btn btn-default')) !!}
                                    </div>
                               </div>
                        {!! Form:: close() !!}
                             </div> <!--  search -->


                               <div class="table-responsive">
                       <table class="table table-striped table-condensed table-bordered">
                         <thead>
                            <tr>
                            <th> house area </th>
                            <th> room size </th>
                            <th> price </th>
                            <th> image </th>  
                            </tr>         
                         </thead>                      
                           @foreach($alldata as $data)
                         <tbody>
                             <tr> 
                              <td> {{$data->house_area}} </td>
                              <td> {{$data->room_size}} sf </td>
                              <td> {{$data->price}} bdt </td>
                              <td> <img class="img-responsive front-image" src="{{ asset('storage/advertise/'.$data->file_name)}}" alt="product"> </td>
                             </tr>
                         </tbody>  
                           @endforeach 
                       </table>  
                      </div>     
                                   {!!$alldata->render() !!}
                           </div>
                   
                        </div>     
   @endsection   

resources/views/mail.blade.php
hello world how are u ???????

resources/views/master.blade.php
<html>
     <head>
          <title> @yield('title') </title>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
         
          <link rel="stylesheet" type="text/css" href="{{ URL::to('first.css')}}">
          <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
          <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
     </head>


     <body>
          <header>
                <div class="container">
                     <div class="row">
                         <div class="col-md-12">
                                  <nav class="navbar navbar-inverse">
                                         <div class="row">
                                            <div class="navbar-header">
                                              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                                      <span class="icon-bar"></span>
                                                      <span class="icon-bar"></span>
                                                      <span class="icon-bar"></span> 
                                                </button>
                                               </div>
                                                 <div class="col-md-6 col-md-offset-4">
                                                     <div class="collapse navbar-collapse" id="myNavbar">
                                                         <ul class="nav navbar-nav">
                                                           <li><a href="#">LOGO</a></li>
                                                           <li><a href="#">HOME</a></li>
                                                           <li><a href="#">ABOUT</a></li>
                                                           <li><a href="#">SERVICE</a></li>
                                                           <li><a href="#">CONTACT</a></li>
                                                         </ul>
                                                     </div>
                                                 </div>
                                           </div>
                                    
                                   </nav>
                          </div>
                     </div>
                </div>
          </header>



          <div class="container">
              <div class="row">
                  <div class="col-md-3">
                      <div class="al-content">
                           <ul class="sidebar-ul">

                                <li> <a href="{{route('login.index')}}"><button type="button" class="btn btn-primary"> Login </button></a> </li>

                                <li> <a href="{{route('registration.index')}}"><button type="button" class="btn btn-primary"> Registration </button></a> </li>

                                <li> <a href="{{route('sentmail.index')}}"><button type="button" class="btn btn-primary"> mail </button></a> </li>

                                
                           
                           </ul>
                      </div>
                  </div>
                  <div class="col-md-9">
                      @yield('content')
                  </div>
              </div>
                 
          </div>



             <footer>

             </footer>
            
             <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
             <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

             <script>
               function myFunction() {
                   if(!confirm("Are You Sure to delete this"))
                   event.preventDefault();
               }
             </script>
     </body>

</html>

resources/views/registration.blade.php
@extends('master')

   @section('title')
        welcome to registration here
   @endsection


   @section('content')
                   <div class="row">
                      <div class="col-md-9 col-md-offset-2">
                       
                       
                         
                                <h3 class="first-heading text-center"><b>Welcome to Registration Here: </b></h3>

                                       

                                                  @if ($errors->any())
                                                       <div class="alert alert-danger">
                                                           <ul>
                                                               @foreach ($errors->all() as $error)
                                                                   <li>{{ $error }}</li>
                                                               @endforeach
                                                           </ul>
                                                       </div>
                                                   @endif
                                               
                                   <p class="messsage text-center" style="color:red"> {{ session('message') }} </p>

                                            
                                             {!! Form::open(array('route'=>'registration.store','files' => true)) !!}
                                              <div class="w3-card login-card">
                                                      <div class="form-group row">
                                                             <div class="col-md-3 col-sm-3 col-xs-3">
                                                                 <label class="contrl-label" for="user_name">Name:</label>
                                                             </div>
                                                             <div class="col-md-9 col-sm-9 col-xs-9">
                                                                  <input type="text" class="form-control" name="user_name"   value="{{ old('user_name') }}" >
                                                              </div>
                                                       </div>

                                                    

                                                       <div class="form-group row">
                                                              <div class="col-md-3 col-sm-3 col-xs-3">
                                                                   <label class="control-label" for="email">Email: </label>
                                                               </div>
                                                               <div class="col-md-9 col-sm-9 col-xs-9">
                                                                    <input type="email" class="form-control" name="email" value="{{ old('email') }}" > 
                                                               </div>
                                                       </div>



                                                       <div class="form-group row">
                                                             <div class="col-md-3 col-sm-3 col-xs-3">
                                                                 <label class="contrl-label" for="gender">Gender:</label>
                                                             </div>
                                                             <div class="col-md-9 col-sm-9 col-xs-9">
                                                                  <input type="radio" name="gender" value="male" checked="checked"> Male
                                                                  <input type="radio" name="gender" value="female"> Female
                                                                  
                                                              </div>
                                                       </div>


                                                     

                                                       <div class="form-group row">
                                                              <div class="col-md-3 col-sm-3 col-xs-3">
                                                                   <label class="control-label" for="birth">Birth Date: </label>
                                                               </div>
                                                               <div class="col-md-9 col-sm-9 col-xs-9">
                                                                    <input type="date" class="form-control" name="birth"  > 
                                                               </div>
                                                       </div>


                                                       <div class="form-group row">
                                                             <div class="col-md-3 col-sm-3 col-xs-3">
                                                                 <label class="contrl-label" for="type">Type:</label>
                                                             </div>
                                                             <div class="col-md-9 col-sm-9 col-xs-9">
                                                                  <input type="radio" name="type" value="renter" checked="checked"> Renter
                                                                  <input type="radio" name="type" value="owner"> Owner
                                                                  
                                                              </div>
                                                       </div>
                                                     
                                                      

                                                    <div class="form-group row">
                                                             <div class="col-md-3 col-sm-3 col-xs-3">
                                                                  <label class="control-label" for="phone">Phone: </label>
                                                              </div>
                                                              <div class="col-md-9 col-sm-9 col-xs-9">
                                                                   <input type="text" class="form-control" name="phone" value="{{ old('phone') }}" > 
                                                              </div>
                                                      </div>




                                                       <div class="form-group row">
                                                              <div class="col-md-3 col-sm-3 col-xs-3">
                                                                   <label class="control-label" for="password">Password: </label>
                                                               </div>
                                                               <div class="col-md-9 col-sm-9 col-xs-9">
                                                                    <input type="password" class="form-control" name="password"  value="{{ old('password') }}" > 
                                                               </div>
                                                       </div>


                                                       <div class="form-group row">
                                                              <div class="col-md-3 col-sm-3 col-xs-3">
                                                                   <label class="control-label" for="password_confirm">Password(again): </label>
                                                               </div>
                                                               <div class="col-md-9 col-sm-9 col-xs-9">
                                                                    <input type="password" class="form-control" name="password_confirm"  value="{{ old('password_confirm') }}" > 
                                                               </div>
                                                       </div>


                                                       <div class="form-group row">
                                                             <div class="col-md-3 col-sm-3 col-xs-3">
                                                                  <label class="control-label" for="address">Address: </label>
                                                              </div>
                                                              <div class="col-md-9 col-sm-9 col-xs-9">
                                                                   <input type="text" class="form-control" name="address" value="{{ old('address') }}"> 
                                                              </div>
                                                       </div>


                                                       <div class="form-group row">
                                                             <div class="col-md-3 col-sm-3 col-xs-3">
                                                                  <label class="control-label" for="image">Image: </label>
                                                              </div>
                                                              <div class="col-md-9 col-sm-9 col-xs-9">
                                                                   <input type="file" class="form-control" name="image" id="image"> 
                                                              </div>
                                                      </div>

                                                     <!--  ,'onclick'=>'return myFunction1()' -->
                                                       {!!Form::submit('submit',array('class'=>'btn btn-success'))!!}
                                                 </div>
                                              {!! Form::close() !!}

                                                 
                         </div>
                       </div>

   @endsection   