routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('login','LoginController');
Route::resource('registration','RegistrationController', ['middleware' => 'CheckLogin']);



Route::group(['middleware' => 'CheckTime'], function()
{
    Route::group(['middleware' => 'CheckLogout'], function()
      {
			Route::resource('advertise','AdvertiseController');
			Route::resource('advcomment','AdvertiseCommentController');
			Route::resource('profile','ProfileController');
			Route::resource('select','SelectController');
			Route::resource('logout','LogoutController');
			Route::resource('delete','DeletedController');
			Route::resource('mypro','MyProfileController');
			Route::resource('statistic','StatisticsController');
      });

});



Route::resource('sentmail','MailController');

resources/views/admin/admin-advcomment.blade.php
@extends('admin.admin-master')


   @section('content2')

  
                        <br><br>
                                   
                             <table class="table">
                                  <tr>
                                  	 <th> user </th>
                                     <th> comment </th>
                                  </tr>                                 
                           @foreach($alldata as $data)  
                                  <tr>
                                  	 <td><a href="{{route('profile.show',$data->user_id)}}"> {{$data->getUserEmail()}} </a></td>
                                     <td> {{$data->comment}} </td>
                                  </tr>      
                          
                           @endforeach 
                                </table>           
                                   {!!$alldata->render() !!}
                   

                 

                          @if ($errors->any())
                               <div class="alert alert-danger">
                                   <ul>
                                       @foreach ($errors->all() as $error)
                                           <li>{{ $error }}</li>
                                       @endforeach
                                   </ul>
                               </div>
                           @endif
                           <p class="messsage text-center" style="color:red"> {{ session('message') }} </p>


                              {!! Form::open(array('route'=>'advcomment.store')) !!}
                                <div class="w3-card login-card">
                                      <div class="form-group row">
                                             <div class="col-md-3 col-sm-3 col-xs-3">
                                                 <label class="contrl-label" for="comment">Make a Comment:</label>
                                             </div>
                                             <div class="col-md-9 col-sm-9 col-xs-9">
                                                  <!-- <input type="text" class="form-control" name="comment"  value="{{ old('comment') }}" required> -->
                                                  <textarea rows="4" cols="50" class="form-control" name="comment">
                                                 
                                                  </textarea>
                                              </div>
                                       </div>

                                     <!--  ,'onclick'=>'return myFunction1()' -->
                                       {!!Form::submit('submit',array('class'=>'btn btn-success'))!!}
                               </div>
                              {!! Form::close() !!}

 

   @endsection   

resources/views/admin/admin-advertise.blade.php
@extends('admin.admin-master')


   @section('content2')
    <h3 class="text-center"> Make an Advertisement </h3>
                    @if ($errors->any())
                         <div class="alert alert-danger">
                             <ul>
                                 @foreach ($errors->all() as $error)
                                     <li>{{ $error }}</li>
                                 @endforeach
                             </ul>
                         </div>
                     @endif
                 
     <p class="messsage text-center" style="color:red"> {{ session('message') }} </p>

              
               {!! Form::open(array('route'=>'advertise.store','files' => true)) !!}
                     <div class="w3-card login-card">
                        <div class="form-group row">
                               <div class="col-md-3 col-sm-3 col-xs-3">
                                   <label class="contrl-label" for="house_area">House Area:</label>
                               </div>
                               <div class="col-md-9 col-sm-9 col-xs-9">
                                    <input type="text" class="form-control" name="house_area"   value="{{ old('house_area') }}" >
                                </div>
                         </div>

                      

                         <div class="form-group row">
                                <div class="col-md-3 col-sm-3 col-xs-3">
                                     <label class="control-label" for="price">Price(bdt): </label>
                                 </div>
                                 <div class="col-md-9 col-sm-9 col-xs-9">
                                      <input type="number" class="form-control" name="price" value="{{ old('price') }}" > 
                                 </div>
                         </div>



                         <div class="form-group row">
                                <div class="col-md-3 col-sm-3 col-xs-3">
                                     <label class="control-label" for="room_size">Room Size(sf): </label>
                                 </div>
                                 <div class="col-md-9 col-sm-9 col-xs-9">
                                      <input type="number" class="form-control" name="room_size" value="{{ old('room_size') }}" > 
                                 </div>
                         </div>
                       
                        

                      <div class="form-group row">
                               <div class="col-md-3 col-sm-3 col-xs-3">
                                    <label class="control-label" for="room_number">Room Number: </label>
                                </div>
                                <div class="col-md-9 col-sm-9 col-xs-9">
                                     <input type="number" class="form-control" name="room_number" value="{{ old('room_number') }}" > 
                                </div>
                        </div>



                         <div class="form-group row">
                               <div class="col-md-3 col-sm-3 col-xs-3">
                                    <label class="control-label" for="address">Address: </label>
                                </div>
                                <div class="col-md-9 col-sm-9 col-xs-9">
                                     <input type="text" class="form-control" name="address" value="{{ old('address') }}"> 
                                </div>
                         </div>


                         <div class="form-group row">
                               <div class="col-md-3 col-sm-3 col-xs-3">
                                    <label class="control-label" for="image">Image: </label>
                                </div>
                                <div class="col-md-9 col-sm-9 col-xs-9">
                                     <input type="file" class="form-control" name="image" id="image"> 
                                </div>
                        </div>

                       
                      
                       <!--  ,'onclick'=>'return myFunction1()' -->
                         {!!Form::submit('submit',array('class'=>'btn btn-success'))!!}
                       </div>
                {!! Form::close() !!}


   @endsection   

resources/views/admin/admin-all-select.blade.php
@extends('admin.admin-master')


   @section('content2')
    <h3 class="text-center"> All Selection </h3>
                     
     <p class="messsage text-center" style="color:red"> {{ session('message') }} </p>

              
                              
        @foreach($alldata as $data)
                
                     <div class="row">
                       <div class="col-md-6 img-content">
                             <img class="advertise-img" src="{{ asset('storage/advertise/'.$data->getFileName())}}" alt="product" class="img-responsive">
                                   <div class="overlay">

                                    
                                      <div class="text">
                            {!! Form::open(['route' => ['select.destroy', $data->id],'method' => 'delete']) !!}
                            {!!Form::hidden('id',$data->id)!!}
                            {!!Form::submit('click for remove',array('class'=>'btn btn-danger','onclick'=>'return myFunction()'))!!}
                            {!! Form::close() !!}
                                      </div>
                                      
                                    </div>  
                       </div>
                       <div class="col-md-6 advertise-content">
                         <div class="table-responsive">          
                            <table class="table">

                             <tr>
                               <th> user name: </th>
                               <td> {{$data->getUserName()}} </td>
                             </tr>

                             <tr>
                               <th> user email: </th>
                               <td> <a href="{{route('profile.show',$data->users_id)}}">{{$data->getUserEmail()}} </a></td>
                             </tr>

                             <tr>
                               <th> user phone: </th>
                               <td> {{$data->getUserPhone()}} </td>
                             </tr>
                            
                              <tr>
                                <th> house area: </th>
                                <td> {{$data->house_area()}} </td>
                              </tr>

                              <tr>
                                <th> price: </th>
                                <td> {{$data->price()}} </td>
                              </tr>

                              <tr>
                                <th> owner name: </th>
                                <td> {{$data->getOwnerName()}} </td>
                              </tr>

                              <tr>
                                <th> owner email: </th>
                                <td> <a href="{{route('profile.show',$data->getOwnerid())}}">{{$data->getOwnerEmail()}} </a></td>
                              </tr>

                               <tr>
                                <th> owner phone: </th>
                                <td> {{$data->getOwnerPhone()}} </td>
                              </tr> 

                               

                           </table>
                       </div>  
                     </div>


                 </div>   
        
        @endforeach 
                        
                {!!$alldata->render() !!}

   @endsection   

resources/views/admin/admin-allmember.blade.php
@extends('admin.admin-master')


   @section('content2')
       <h3 class="text-center"> All Users </h3>

         <p class="messsage text-center" style="color:red"> {{ session('message') }} </p>
               @foreach($alldata as $data)
                       
                            <div class="row">
                              <div class="col-md-4 allprofile">
                                 <img  src="{{ asset('storage/upload/'.$data->file_name)}}" alt="profile image" class=" img-responsive">
                              </div>

                              <div class="col-md-8 ">
                                <div class="table-responsive">          
                                   <table class="table">
                                    <tr>
                                        <th> name :</th>
                                        <td> {{$data->user_name}} </td>
                                    </tr>

                                    <tr>
                                        <th> email :</th>
                                        <td> {{$data->email}} </td>
                                    </tr>

                                    <tr>
                                        <th> contact :</th>
                                        <td> {{$data->phone}} </td>
                                    </tr>

                                    <tr>
                                        <th> type :</th>
                                        <td> {{$data->type}} </td>
                                    </tr>

                                    <tr>
                                        <th> status :</th>
                                        <td> <?php
                                              if($data->status)   
                                                 echo "active";
                                               else echo "deactive";
                                              ?> </td>
                                    </tr>
                                   
                                     <tr>
                                         <th> action :</th>
                                         <td><b> <a href="{{route('profile.edit',$data->id)}} " class="member-action"> <?php
                                              if($data->status)   
                                                 echo "click for deactive";
                                               else echo "click for active";
                                              ?> </a> </b></td>
                                     </tr>

                                  </table>
                              </div>  
                            </div>


                        </div>   
                         <br>
               @endforeach 
                               
                       {!!$alldata->render() !!}
     
   @endsection   

resources/views/admin/admin-deleted-advertise.blade.php
@extends('admin.admin-master')


   @section('content2')

    <h3 class="text-center"> All Deleted Advertisements </h3>

       <p class="messsage text-center" style="color:red"> {{ session('message') }} </p>
                     
                     <div class="table-responsive">
                       <table class="table table-striped table-condensed table-bordered">
                       	 <thead>
                       	    <tr>
	                       	 	<th> owner </th>
	                       	 	<th> house area </th>
	                       	 	<th> address </th>
	                       	 	<th> room size </th>
	                       	 	<th> price </th>
	                       	 	<th> image </th>	
                            </tr>         
                         </thead>                      
                           @foreach($alldata as $data)
                         <tbody>
                             <tr>
	                            <td><a href="{{route('profile.show',$data->user_id)}}"> {{$data->getUserEmail()}} </a></td> 
	                            <td> {{$data->house_area}} </td>
	                            <td> {{$data->address}} </td>
	                            <td> {{$data->room_size}} sf </td>
	                            <td> {{$data->price}} bdt </td>
	                            <td> <img class="img-responsive" src="{{ asset('storage/advertise/'.$data->file_name)}}" alt="product"> </td>
                             </tr>
                         </tbody>  
                           @endforeach 
                       </table>  
                      </div>     
                                   {!!$alldata->render() !!}
                   
   @endsection   

resources/views/admin/admin-home.blade.php
@extends('admin.admin-master')


   @section('content2')

    <h3 class="text-center"> All Advertisements </h3>

       <p class="messsage text-center" style="color:red"> {{ session('message') }} </p>


                                   
                                                 
                           @foreach($alldata as $data)
                                   
                                        <div class="row">
                                          <div class="col-md-6 img-content">
                                             <img class="advertise-img" src="{{ asset('storage/advertise/'.$data->file_name)}}" alt="product" class="img-responsive">
                                                 <div class="overlay">

                                                  <a href="{{route('select.show',$data->id)}}">
                                                    <div class="text">
                                                       add to cart 
                                                    </div>
                                                    </a>
                                                  </div>   
                                          </div>
                                          <div class="col-md-6 advertise-content">
                                            <div class="table-responsive">          
                                               <table class="table">
                                              <tr>
                                                 <th> owner </th>
                                                 <td> <a href="{{route('profile.show',$data->user_id)}}"> {{$data->getUserEmail()}} </a> </td>
                                              </tr>
                                                <tr>
                                                 <th> phone </th>
                                                 <td> {{$data->getUserPhone()}} </td>
                                              </tr>
                                               <tr>
                                                 <th> house area: </th>
                                                 <td> {{$data->house_area}} </td>
                                              </tr>
                                               <tr>
                                                 <th> price: </th>
                                                 <td> {{$data->price}} bdt </td>
                                              </tr>
                                               <tr>
                                                 <th> room size: </th>
                                                 <td> {{$data->room_size}} sf </td>
                                              </tr>
                                              <tr>
                                                 <th> room number: </th>
                                                 <td> {{$data->room_number}} </td>
                                              </tr>
                                              <tr>
                                                 <th> address </th>
                                                 <td> {{$data->address}} </td>
                                              </tr>
                                              <tr>
                                                 <th> comment </th>
                                                 <td> 
                                                    <a href="{{route('advcomment.show',$data->id)}}"><button type="button" class="btn btn-primary"> click here </button></a>
                                                  </td>
                                              </tr>

                                              </table>
                                          </div>  
                                        </div>


                                    </div>   
                          
                           @endforeach 
                                           
                                   {!!$alldata->render() !!}
                   
   @endsection   

resources/views/admin/admin-master.blade.php
@extends('master')

   @section('title')
        ***Admin Page
   @endsection


   @section('content')
                   <div class="row">
                   	 <h1 class="text-center"> Admin Panel </h1>
                     <div class="col-md-9 right-side">
                     	  @yield('content2')
                     </div>

                     <div class="col-md-3 ">
                           <ul class="sidebar-ul">
                                <li> <a href="{{route('login.create')}}"><button type="button" class="btn btn-primary"> home page </button></a> </li>

                                <li> <a href="{{route('advertise.index')}}"><button type="button" class="btn btn-primary"> new advertise </button></a> </li>

                                <li> <a href="{{route('profile.index')}}"><button type="button" class="btn btn-primary"> all member </button></a> </li>

                                <li> <a href="{{route('select.index')}}"><button type="button" class="btn btn-primary"> all selection </button></a> </li>

                                <li> <a href="{{route('select.create')}}"><button type="button" class="btn btn-primary"> my selection </button></a> </li>

                                <li> <a href="{{route('advertise.create')}}"><button type="button" class="btn btn-primary"> my advertise </button></a> </li>

                                <li> <a href="{{route('delete.index')}}"><button type="button" class="btn btn-primary"> deleted advertise </button></a> </li>

                                <li> <a href="{{route('mypro.index')}}"><button type="button" class="btn btn-primary"> my profile </button></a> </li>


                                <li> <a href="{{route('statistic.index')}}"><button type="button" class="btn btn-primary"> statistic </button></a> </li>

                                <li> <a href="{{route('logout.index')}}"><button type="button" class="btn btn-primary"> logout </button></a> </li>



                                
                           
                           </ul>
                     </div>
                                 
                   
                    </div>     
   @endsection   

resources/views/admin/admin-my-advertise.blade.php
@extends('admin.admin-master')


   @section('content2')

    <h3 class="text-center"> My Advertisements </h3>

       <p class="messsage text-center" style="color:red"> {{ session('message') }} </p>


                                   
                                                 
                           @foreach($alldata as $data)
                                   
                                        <div class="row">
                                          
                                          <div class="col-md-6 advertise-content">
                                            <div class="table-responsive">          
                                               <table class="table">
                                              <tr>
                                                 <th> owner </th>
                                                 <td> <a href="{{route('profile.show',$data->user_id)}}"> {{$data->getUserEmail()}} </a> </td>
                                              </tr>
                                                <tr>
                                                 <th> phone </th>
                                                 <td> {{$data->getUserPhone()}} </td>
                                              </tr>
                                               <tr>
                                                 <th> house area: </th>
                                                 <td> {{$data->house_area}} </td>
                                              </tr>
                                               <tr>
                                                 <th> price: </th>
                                                 <td> {{$data->price}} bdt </td>
                                              </tr>
                                               <tr>
                                                 <th> room size: </th>
                                                 <td> {{$data->room_size}} sf </td>
                                              </tr>
                                              <tr>
                                                 <th> room number: </th>
                                                 <td> {{$data->room_number}} </td>
                                              </tr>
                                              <tr>
                                                 <th> address </th>
                                                 <td> {{$data->address}} </td>
                                              </tr>
                                               </table>
                                          </div>  
                                        </div>
                                       
                                        <div class="col-md-6 img-content">
                                           <img class="advertise-img" src="{{ asset('storage/advertise/'.$data->file_name)}}" alt="product" class="img-responsive">
                                  
                                    <div class="overlay">

                                     
                                       <div class="text">
                             <a href="{{route('advertise.edit',$data->id)}}" onclick="return myFunction()"> <button type="button" class="btn btn-danger"> click for delete </button> </a>           
                             
                                       </div>
                                       
                                     </div>    
                                         </div> 

                                    </div>   
                          
                           @endforeach 
                                           
                                   {!!$alldata->render() !!}
                   
   @endsection   

resources/views/admin/admin-my-profile-show.blade.php
@extends('admin.admin-master')


   @section('content2')
       <h3 class="text-center"> My Info </h3>

         <p class="messsage text-center" style="color:red"> {{ session('message') }} </p>


          <div class="row">
          	<div class="col-md-6 col-md-offset-3">
              <div class="card own-profile">
                 <img  src="{{ asset('storage/upload/'.$data->file_name)}}" alt="profile image" class=" img-responsive">

                 <h4><b> {{$data->user_name}} </b></h4>
                 <p class="own-email">  {{$data->email}}     </p> 
                 <p>  {{$data->phone}}     </p>
                 <p>  type: {{$data->type}}     </p>
                 <p>  address: {{$data->address}}     </p>
                 <p>  birth: {{$data->birth}}     </p>
                 <p>  gender: {{$data->gender}}     </p>

                 <a href="{{route('mypro.edit',$data->id)}}" class="edit-btn"><button type="button" class="btn btn-primary"> click for edit </button></a>
              </div>
             </div> 
          </div>
                       
                            
     
   @endsection   

resources/views/admin/admin-my-selection.blade.php
@extends('admin.admin-master')


   @section('content2')
    <h3 class="text-center"> My Selection </h3>
                     
     <p class="messsage text-center" style="color:red"> {{ session('message') }} </p>

              
                              
        @foreach($alldata as $data)
                
                     <div class="row">
                       <div class="col-md-6 img-content">
                             <img class="advertise-img" src="{{ asset('storage/advertise/'.$data->getFileName())}}" alt="product" class="img-responsive">
                                   <div class="overlay">

                                    
                                      <div class="text">
                            {!! Form::open(['route' => ['select.destroy', $data->id],'method' => 'delete']) !!}
                            {!!Form::hidden('id',$data->id)!!}
                            {!!Form::submit('click for remove',array('class'=>'btn btn-danger','onclick'=>'return myFunction()'))!!}
                            {!! Form::close() !!}
                                      </div>
                                      
                                    </div>  
                       </div>
                       <div class="col-md-6 advertise-content">
                         <div class="table-responsive">          
                            <table class="table">

                             <tr>
                               <th> user name: </th>
                               <td> {{$data->getUserName()}} </td>
                             </tr>

                             <tr>
                               <th> user email: </th>
                               <td> <a href="{{route('profile.show',$data->users_id)}}">{{$data->getUserEmail()}} </a></td>
                             </tr>

                             <tr>
                               <th> user phone: </th>
                               <td> {{$data->getUserPhone()}} </td>
                             </tr>
                            
                              <tr>
                                <th> house area: </th>
                                <td> {{$data->house_area()}} </td>
                              </tr>

                              <tr>
                                <th> price: </th>
                                <td> {{$data->price()}} </td>
                              </tr>

                              <tr>
                                <th> owner name: </th>
                                <td> {{$data->getOwnerName()}} </td>
                              </tr>

                              <tr>
                                <th> owner email: </th>
                                <td> <a href="{{route('profile.show',$data->getOwnerid())}}">{{$data->getOwnerEmail()}} </a></td>
                              </tr>

                               <tr>
                                <th> owner phone: </th>
                                <td> {{$data->getOwnerPhone()}} </td>
                              </tr> 

                               

                           </table>
                       </div>  
                     </div>


                 </div>   
        
        @endforeach 
                        
                {!!$alldata->render() !!}

         <?php  if(count($alldata)==0)  { ?>
             <h3 class="text-center no-data"> no data </h3>

         <?php  }  ?>  
   @endsection   